######################################################################
# Automatically generated by qmake (2.01a) Thu Jun 14 14:22:41 2012
######################################################################

TEMPLATE = app
TARGET = lmp3
DEPENDPATH += .
INCLUDEPATH += .
QT += phonon

# Input
HEADERS += libraryManager.h mediaPlayerUI.h ../tiny-xml/tinyxml2.h
SOURCES += libraryManager.cpp \
           main.cpp \
           mediaPlayerUI.cpp \
           ../tiny-xml/tinyxml2.cpp
