######################################################################
# Automatically generated by qmake (2.01a) Wed May 23 16:33:57 2012
######################################################################

TEMPLATE = app
TARGET = lightweight-mp3
DEPENDPATH += .
INCLUDEPATH += .
QT += phonon

# Input
HEADERS += mediaPlayerUI.h
SOURCES += main.cpp mediaPlayerUI.cpp
